In the preparation of this proposal, I used several AI-powered tools to assist with content generation, organization, and refinement.

I used Claude AI (Anthropic) extensively through the Cursor IDE to help structure and draft sections of this proposal. Specifically, I provided the AI with my literature review draft, technical analysis document (PREDICTIVE_SCALING_ANALYSIS.md), and the instructor's structural requirements. The AI then helped me transform these materials into a coherent proposal following the required format. I used the AI to generate initial drafts of the Abstract, Introduction, Problem, Motivation, Objectives, and Schedule sections based on my source materials and the scientific citations I had already prepared. Throughout this process, I reviewed each generated section, made modifications to ensure technical accuracy, adjusted phrasing to match my voice, and verified that all citations were correctly integrated and accurately represented the referenced research.

I also used ChatGPT (OpenAI) during the earlier research phase to help summarize academic papers and identify key themes across the literature on cloud IDE platforms, predictive scaling, and educational technology. These summaries helped me understand the landscape before I created my literature review draft.

For bibliography management, I used Zotero to collect and organize academic papers. I manually converted BibTeX citations to the YAML format required by the Typst template.

I have carefully checked all texts created with these tools to ensure that they are correct and make sense. All technical details about Theia Cloud, Kubernetes operators, and the implementation architecture are based on my own analysis of the codebase and documentation. The schedule and objectives reflect my own assessment of feasible work items for the thesis timeline.
